### ISSUE TITLE
Support Visual Studio 17 2022

### ISSUE THREAD

**Issue by EwoutH** [winlibs/libiconv#12]
Support for Visual Studio 2022 (`MSVC17`) would be awesome!

**Comment by scoder** [comment]
I second this. Upgrading to libiconv 1.17 would probably help, as that is the latest release.

**Comment by cmb69** [comment]
We already updated to libiconv 1.17 a while ago. However, the build folders are not part of libiconv (actually, they don't offer any native Windows build system support; only autoconf is supported by upstream). Anyhow, PR #13 has just been merged, so this ticket can be closed.
